name: CI-CD

on:
  push:
    branches:
      - dev

env:
  S3_BUCKET_NAME: wanted-preonboarding-s3


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - run: echo "${{secrets.APPLICATION_CONF_1}}" > ./src/main/resources/application-prod.yml
      - uses: actions/upload-artifact@v4
        with:
          name: application-prod.yml
          path: ./src/main/resources/application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Copy logback
        run: cp ./src/main/resources/logback-prod.xml ./deploy/logback.xml

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script app Start
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./prscs.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./prscs.zip s3://$S3_BUCKET_NAME/

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws deploy create-deployment
          --application-name wanted-code-deploy
          --deployment-group-name wanted-deploy-group
          --file-exists-behavior OVERWRITE
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=prscs.zip

